# Generated by Django 6.0.2 on 2026-04-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="extracted_skills",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="full_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
