# Generated by Django 6.0.2 on 2026-04-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_resume_extracted_skills_resume_full_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="compatibility_score",
            field=models.IntegerField(default=0),
        ),
    ]
