# Generated by Django 6.0.2 on 2026-04-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0004_resume_compatibility_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="resume_sentiment",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
