# Generated by Django 6.0.2 on 2026-04-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0006_resume_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="ai_suggestions",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
