# Generated by Django 6.0.2 on 2026-04-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_resume_ai_suggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='ai_suggestions',
        ),
    ]
