# Generated by Django 6.0.2 on 2026-04-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0008_remove_resume_ai_suggestions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
