# Generated by Django 6.0.2 on 2026-04-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0009_userprofile_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="resume_sentiment",
        ),
    ]
